# Generated by Django 4.2.3 on 2024-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('song', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
